ci:
  autoupdate_commit_msg: "MAINT: autoupdate pre-commit hooks"
  autoupdate_schedule: quarterly

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v6.8.1
    hooks:
      - id: cspell

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.6.1
    hooks:
      - id: editorconfig-checker

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.0
    hooks:
      - id: prettier
